version: '3.1'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn run dev
  postgres: 
    image: postgres
    env_file:
      - ./.env
    ports:
      - $DB_PORT
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - /data:/var/lib/postgresql/data